name: Run Android Emulator in Docker

on: [push, pull_request]

jobs:
  run-docker:
    runs-on: ubuntu-latest  # GitHub provides Ubuntu runners with Docker support
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for ARM-based emulators, if needed)
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm

      # 🔹 Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 🔹 Cache Docker Layers for Faster Builds
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # 🔹 Build and Push Docker Image with Cache
      - name: Build Docker Image
        run: |
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            -t thangnguyen0495/android-appium-test:latest .

      # 🔹 Run the Container
      - name: Start Docker Container
        run: |
          docker run -d --name emulator-container --privileged \
            -p 5555:5555 -p 5037:5037 -p 4723:4723 \
            thangnguyen0495/android-appium-test:latest

      - name: Wait for Emulator to Start
        run: |
          sleep 60  # Wait for the emulator to boot up
          docker logs emulator-container

      - name: Check ADB Devices
        run: |
          docker exec emulator-container adb devices