
name: Run Android Emulator in Docker
on:
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-latest  # GitHub provides Ubuntu runners with Docker support

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Docker Container
        run: |
          docker run -d --name emulator-container --privileged \
            thangnguyen0495/android-appium:latest

      - name: Wait for Emulator to Start
        run: |
          sleep 60
          docker logs emulator-container
      - name: Check ADB Devices
        run: |
          docker exec emulator-container adb devices
          docker exec emulator-container bash -c "cd /app && mvn install -DskipTests"
          docker exec emulator-container bash -c "cd /app && mvn test -DsuiteFile=test.xml"