name: Run Android Emulator in Docker (Mount)
on:
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Docker Container with Volume Mount
        run: |
          docker run -d --name chrome-container --privileged \
            -v ${{ github.workspace }}:/app \
            thangnguyen0495/browser-selenium:latest tail -f /dev/null

#      - name: Setup tmate session (debugging)
#        run: |
#          sudo apt-get install -y tmate
#          tmate -S /tmp/tmate.sock new-session -d  # Start in detached mode
#          tmate -S /tmp/tmate.sock wait tmate-ready
#          echo "SSH connection string:"
#          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
#          echo "Web connection:"
#          tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
#        continue-on-error: true
#
      - name: Start SSH session
        uses: mxschmitt/action-tmate@v3
        env:
          TMATE_IDLE_MESSAGE: |
            ⚠️ SSH Debugging Session Started
            👉 SSH into the runner using the command above
            💡 Type 'exit' to end the session and continue the workflow.r

      - name: Run Maven Install inside Container
        run: |
          docker exec chrome-container bash -c "cd /app && mvn install -DskipTests"

      - name: Run Maven Tests inside Container
        run: |
          docker exec chrome-container bash -c "cd /app && mvn test -DsuiteFile=test.xml"
