name: Run Android Emulator in Docker (Mount)
on:
  workflow_dispatch:
    inputs:
      debug:
        description: "Enable SSH debugging"
        required: true
        default: "OFF"

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Docker Container with Volume Mount
        run: |
          docker run -d --name emulator-container --privileged \
            -v ${{ github.workspace }}:/app \
            thangnguyen0495/android-appium:latest tail -f /dev/null

      - name: Verify Container Status
        run: |
          docker ps -a

      - name: Start SSH session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event.inputs.debug == 'ON' }}
        env:
          TMATE_IDLE_MESSAGE: |
            ⚠️ SSH Debugging Session Started
            👉 SSH into the runner using the command above
            💡 Type 'exit' to end the session and continue the workflow.

      - name: Start emulator and appium server
        run: |
          docker exec emulator-container chmod +x /app/start-emulator.sh
          docker exec emulator-container bash /app/start-emulator.sh

      - name: Run Maven Install inside Container
        run: |
          docker exec emulator-container bash -c "cd /app && mvn install -DskipTests"

      - name: Run Maven Tests inside Container
        run: |
          docker exec emulator-container bash -c "cd /app && mvn test -DsuiteFile=test.xml"
