name: Run Android Emulator in Docker (Mount)
on:
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Docker Container with Volume Mount
        run: |
          docker run -d --name chrome-container --privileged \
            -v ${{ github.workspace }}:/app \
            thangnguyen0495/chrome-selenium:latest tail -f /dev/null

      - name: Run Maven Install inside Container
        run: |
          docker exec chrome-container bash -c "cd /app && mvn install -DskipTests"

      - name: Run Maven Tests inside Container
        run: |
          docker exec chrome-container bash -c "cd /app && mvn test -DsuiteFile=test.xml"
