name: Run Android Emulator in Docker (Mount)
on:
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Docker Container with Volume Mount
        run: |
          docker run -d --name emulator-container --privileged \
            -v ${{ github.workspace }}:/app \
            thangnguyen0495/android-appium:latest tail -f /dev/null

      - name: Verify Container Status
        run: |
          docker ps -a

      - name: Setup tmate session (debugging)
        run: |
          sudo apt-get install -y tmate
          tmate -S /tmp/tmate.sock new-session -d  # Start in detached mode
          tmate -S /tmp/tmate.sock wait tmate-ready
          echo "SSH connection string:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          echo "Web connection:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
        continue-on-error: true

      - name: Start emulator and appium by bash scripts
        run: |
          docker exec emulator-container chmod +x /app/entrypoint.sh
          docker exec emulator-container /app/entrypoint.sh

      - name: Run Maven Install inside Container
        run: |
          docker exec emulator-container bash -c "cd /app && mvn install -DskipTests"

      - name: Run Maven Tests inside Container
        run: |
          docker exec emulator-container bash -c "cd /app && mvn test -DsuiteFile=test.xml"
